// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARt5qcJcoOXYRJ0ri9UH3_6dLxvimw7Hw',
    appId: '1:156421846422:web:d8d6fbfa13a498766719b7',
    messagingSenderId: '156421846422',
    projectId: 'clean-my-town-backend',
    authDomain: 'clean-my-town-backend.firebaseapp.com',
    databaseURL: 'https://clean-my-town-backend-default-rtdb.firebaseio.com',
    storageBucket: 'clean-my-town-backend.appspot.com',
    measurementId: 'G-NJH3Q49KCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6t68EbGjuzBJLEfgjJhiX20nW467u4Yg',
    appId: '1:156421846422:android:ed6bde62ac4527c96719b7',
    messagingSenderId: '156421846422',
    projectId: 'clean-my-town-backend',
    databaseURL: 'https://clean-my-town-backend-default-rtdb.firebaseio.com',
    storageBucket: 'clean-my-town-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0go9Rq6sbNOxFcC7_roY97cshxXPoxQ',
    appId: '1:156421846422:ios:bcca5ff8ee10ae766719b7',
    messagingSenderId: '156421846422',
    projectId: 'clean-my-town-backend',
    databaseURL: 'https://clean-my-town-backend-default-rtdb.firebaseio.com',
    storageBucket: 'clean-my-town-backend.appspot.com',
    iosClientId: '156421846422-vrokru6sq9cni12ai6soe5vtglvlc230.apps.googleusercontent.com',
    iosBundleId: 'com.example.oruMobiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0go9Rq6sbNOxFcC7_roY97cshxXPoxQ',
    appId: '1:156421846422:ios:bcca5ff8ee10ae766719b7',
    messagingSenderId: '156421846422',
    projectId: 'clean-my-town-backend',
    databaseURL: 'https://clean-my-town-backend-default-rtdb.firebaseio.com',
    storageBucket: 'clean-my-town-backend.appspot.com',
    iosClientId: '156421846422-vrokru6sq9cni12ai6soe5vtglvlc230.apps.googleusercontent.com',
    iosBundleId: 'com.example.oruMobiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0sdLA4BfxHwpn4CKXMIIbPx5hKmsxMao',
    appId: '1:156421846422:web:9b5efb3b476a37086719b7',
    messagingSenderId: '156421846422',
    projectId: 'clean-my-town-backend',
    authDomain: 'clean-my-town-backend.firebaseapp.com',
    databaseURL: 'https://clean-my-town-backend-default-rtdb.firebaseio.com',
    storageBucket: 'clean-my-town-backend.appspot.com',
    measurementId: 'G-JD543GYP69',
  );
}
